# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-31 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import morango.models.fields.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20240322_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprogressnotification',
            name='assessment_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='learnerprogressnotification',
            name='assessment_num_answered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerprogressnotification',
            name='assessment_num_correct',
            field=models.IntegerField(null=True),
        ),
    ]
