# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-08-31 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0015_facilityuser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitydataset',
            name='learner_can_view_lessons',
            field=models.BooleanField(default=True),
        ),
    ]
