# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0016_auto_20220907_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityuser',
            name='exam_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
