# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-11-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0017_auto_20220914_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('kolibriauth.collection',),
        ),
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('facility', 'Facility'), ('classroom', 'Classroom'), ('learnergroup', 'Learner group'), ('adhoclearnersgroup', 'Ad hoc learner group within a class')], max_length=20),
        ),
    ]
