# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0023_change_extra_fields_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
