# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0026_auto_20231127_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='kind',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('classroom assignable coach', 'Classroom Assignable Coach'), ('edulutionCoach', 'edulutionCoach')], max_length=26),
        ),
    ]
