# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0027_auto_20240502_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitydataset',
            name='learner_can_view_lessons',
            field=models.BooleanField(default=False),
        ),
    ]
