# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-11 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_contentrequest_source_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
