# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-19 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import morango.models.fields.uuids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kolibriauth', '0026_auto_20231127_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssessment',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('question_count', models.IntegerField()),
                ('question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('seed', models.IntegerField(default=1)),
                ('learners_see_fixed_order', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date_activated', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('date_archived', models.DateTimeField(blank=True, default=None, null=True)),
                ('data_model_version', models.SmallIntegerField(default=2)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examassessment', to='kolibriauth.Collection')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessment', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityDataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAssignmentAssessment',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_exams', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_exams', to='kolibriauth.Collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityDataset')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentassessments', to='assessment.ExamAssessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualSyncableExam',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('exam_id', models.UUIDField()),
                ('serialized_exam', kolibri.core.fields.JSONField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to='kolibriauth.Collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to='kolibriauth.FacilityDataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
