# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-02 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import morango.models.fields.uuids
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolibriauth', '0028_facilitydataset_learner_can_view_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.UUIDField(null=True)),
                ('assessment_map', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(null=True)),
                ('summarylog_id', models.UUIDField(null=True)),
                ('assessment_id', models.UUIDField(null=True)),
                ('mastery_criterion', kolibri.core.fields.JSONField(default={})),
                ('start_timestamp', kolibri.core.fields.DateTimeTzField()),
                ('end_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('completion_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('mastery_level', models.IntegerField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('time_spent', models.FloatField(null=True)),
                ('question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssessment',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('question_count', models.IntegerField()),
                ('question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('seed', models.IntegerField(default=1)),
                ('assignments', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('channel_id', models.UUIDField(null=True)),
                ('learners_see_fixed_order', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date_activated', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('date_archived', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_data', kolibri.core.fields.JSONField(blank=True, default={})),
                ('attempt_count', models.IntegerField(default=0, null=True)),
                ('current_question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('previous_question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('topicwise_weightage', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('current_question_count', models.IntegerField(default=0, null=True)),
                ('current_questions_limit', models.IntegerField(default=0, null=True)),
                ('data_model_version', models.SmallIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAssessmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('learner_id', models.CharField(default='1', max_length=200)),
                ('channel_id', models.UUIDField(null=True)),
                ('new_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_activated', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('date_archived', models.DateTimeField(blank=True, default=None, null=True)),
                ('assessment_map', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('current_assessment_type', models.CharField(max_length=200, null=True)),
                ('current_assessment_level', models.CharField(max_length=200, null=True)),
                ('last_assessment_type', models.CharField(max_length=200, null=True)),
                ('last_assessment_level', models.CharField(max_length=200, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessmentgrouplist', to='kolibriauth.Collection')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessementfacilityuser', to=settings.AUTH_USER_MODEL)),
                ('current_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assessment_group', to='assessment.ExamAssessment')),
                ('last_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_assessment_group', to='assessment.ExamAssessment')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignmentAssessment',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_exams', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_exams', to='kolibriauth.Collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityDataset')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentassessments', to='assessment.ExamAssessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualSyncableExam',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('exam_id', models.UUIDField()),
                ('serialized_exam', kolibri.core.fields.JSONField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to='kolibriauth.Collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to='kolibriauth.FacilityDataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_syncable_exams_assessment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='examassessment',
            name='assessment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_assessments', to='assessment.ExamAssessmentGroup'),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examassessment', to='kolibriauth.Collection'),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityDataset'),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessmentlearner', to=settings.AUTH_USER_MODEL),
        ),
    ]
