# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-22 12:02
from __future__ import unicode_literals

from django.db import migrations
import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassessment',
            name='assignments',
            field=kolibri.core.fields.JSONField(blank=True, default=[]),
        ),
    ]
