# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-01 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kolibriauth', '0026_auto_20231127_0911'),
        ('assessment', '0003_auto_20240331_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassessmentgroup',
            name='_morango_dirty_bit',
        ),
        migrations.RemoveField(
            model_name='examassessmentgroup',
            name='_morango_partition',
        ),
        migrations.RemoveField(
            model_name='examassessmentgroup',
            name='_morango_source_id',
        ),
        migrations.RemoveField(
            model_name='examassessmentgroup',
            name='dataset',
        ),
        migrations.AddField(
            model_name='examassessment',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessmentlearner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examassessmentgroup',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examassessmentgrouplist', to='kolibriauth.Collection'),
        ),
        migrations.AlterField(
            model_name='examassessmentgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examassessmentgroup',
            name='learner_id',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
