# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_examassessmentgroup_new_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.UUIDField(null=True)),
                ('assessment_map', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examassessmentgroup',
            name='current_assessment_level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examassessmentgroup',
            name='current_assessment_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examassessmentgroup',
            name='last_assessment_level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examassessmentgroup',
            name='last_assessment_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examassessmentgroup',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
