# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20240503_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassessment',
            name='attempt_count',
            field=models.IntegerField(null=True),
        ),
    ]
