# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_examassessment_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassessment',
            name='attempt_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
