# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20240503_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(null=True)),
                ('summarylog_id', models.UUIDField(null=True)),
                ('assessment_id', models.UUIDField(null=True)),
                ('mastery_criterion', kolibri.core.fields.JSONField(default={})),
                ('start_timestamp', kolibri.core.fields.DateTimeTzField()),
                ('end_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('completion_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('mastery_level', models.IntegerField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('time_spent', models.FloatField(null=True)),
                ('question_sources', kolibri.core.fields.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examassessment',
            name='current_question_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='current_question_sources',
            field=kolibri.core.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='current_questions_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='previous_question_sources',
            field=kolibri.core.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='examassessment',
            name='topicwise_weightage',
            field=kolibri.core.fields.JSONField(blank=True, default=[]),
        ),
    ]
